### ISSUE TITLE
Event date and time intervals

### ISSUE THREAD

**Issue by shukuru** [iamiddy/Dockerfiles#10]
if am not getting it wrong, this system is for booking for events.. if i have a wedding and i need a photographer, this is where i can search for the provider.. "Days" field in the search does not seem to be applicable to me.. unless if i have an event that takes more than one day (which are few)..and even if they are, then it might be at different times.. lets say i need a photographer today at 10am-11am, then tomorrow at 4pm-5pm.. or for another scenario, even if its one day, i think there must be somewhere to put event start time and end time.. so that a photographer cant be booked for the whole day, while can serve to clients at the same day, different times.. hope am understood..

**Comment by iamiddy** [comment]
That's a good point and  will limit results options, thanks for catching it.
Bottom line don`t  use days to indicate the event end-date, this must be fixed
