### ISSUE TITLE
place names upon searching

### ISSUE THREAD

**Issue by shukuru** [iamiddy/Dockerfiles#9]
The first field in the form is written where in Tanzania.. It does not limit the user on place names.. do you mean i can even put my street name like kambi ya fisi? or it goes up to district levels only? for that case I would propose a drop down instead of just an open search..

**Comment by iamiddy** [comment]
Yes, the where is open to every where in Tanzania, as long as there are providers listed on those areas. It could be true that someone needs providers from their street, so we don`t see why limit them.

For that reason a dropdown is not a viable option, but also during registration we don`t want to limit our providers to a generic location, and make them loose all the local businesses/customers

**Comment by shukuru** [comment]
Now the concept for where is confusing me a little bit.. where meaning the location of the service provider or the location of my event? For example, I am at Mwenge and I need a service provider.. but I can get a service provider from Ilala.. So I assume in "where" field I should fill "Mwenge", a place where my event will happen, so it does not matter where will i get my service provider.. For example last week, Rainbow got a service to provide from Dodoma, so it does not matter where the service provider is located.. I dont know if i am getting it wrong..

**Comment by iamiddy** [comment]
There will be an additional feature of the to address that in the future alpha releases, where you could enquire providers by location the event or closest to that location by Miles/KMs. this could returns all providers country-wide, and you can filter them based on other criteria. , or use global search to search providers by their name or business descriptions
